Telefonica/mistica-ios

Mistica/Source/Components/EmptyState/EmptyState.swift, Mistica/Source/Components/EmptyState/EmptyStateConfiguration.swift, Mistica/Source/Components/EmptyState/Internals/EmptyStateButtons.swift, Mistica/Source/Components/EmptyState/Internals/EmptyStateContentBase.swift, Mistica/Tests/MisticaTests/UI/EmptyStatesTests.swift, MisticaCatalog/Source/ComponentsCatalogs/UICatalogEmptyStateViewController.swift
[IOS-7012](https://jira.tid.es/browse/IOS-7012) Empty state buttons handler not working
Assign the handler defined by the developer to the desired buttons of the component
We did it by assigning the handler defined outside of the component to the component vars defined for that
Downloading the catalog and inside the Empty state component tap any button.
https://install.appcenter.ms/orgs/tuenti-organization/apps/mistica-ios/distribution_groups/public
[Last version](https://install.appcenter.ms/orgs/tuenti-organization/apps/mistica-ios/distribution_groups/public)
https://user-images.githubusercontent.com/43632903/133466065-9f58fda4-808e-408e-bfea-783f5b146a9e.mov
=> fix(EmptyState): Empty state buttons handler IOS-7012

Mistica/Source/Components/RadioButton/RadioButton.swift
Radio button accessibility traits were not being correctly set, so when the radio button was selected there was no indication or way to tell from an accessibility inspector (like Appium)
Before, the element was being detected as `XCUIElementTypeOther`:
Now, the element is detected as `XCUIElementTypeButton`, with `value=1` when selected:
=> fix(RadioButton): Accesibility traits

Sources/MisticaCommon/Assets/AssetToolkit+Image.swift, Sources/MisticaCommon/Assets/AssetToolkit+UIImage.swift, Sources/MisticaCommon/Assets/DefaultMisticaBrandAssets.swift, Sources/MisticaCommon/Assets/MisticaBrandAssets.swift
https://jira.tid.es/browse/IOS-7644
I want to use this dependency (instead of mistica-ios-swiftui) in Zeus project. I've noticed that `MisticaBrandAssets` protocol includes some **common assets** plus the _branded_ ones. This protocol allows to customize the _branded_ assets when we use a custom brand instead of the existent ones (movistar, etc) so having to implement common resources every time we create a custom brand does not make sense.
What did I do??? I've just removed the common assets since they will be shared internally for all our brands included the custom ones.
I've not considered this a breaking change since the old clients will just to update and remove (if they want; the should) the excluded properties in the protocol.
=> fix(Assets): IOS-7644 Exclude common assets from  protocol

MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift, Sources/Mistica/Components/Sheet/Model/SheetConfiguration.swift, Sources/Mistica/Components/Sheet/View/SheetView.swift
Hi there!
This PR is a hotfix to map the icon parameter of the rows in the Sheet component. Until now it was thought that it was not going to be necessary to include it but we already have the definition and it is required for 13.8.
This parameter will come with two icon urls, one for the light mode and one for the dark mode.
=> IOS-7705 Allow icons from url in Sheet

MisticaCatalog/Source/Catalog/MisticaSwiftUI/Components/DataCardCatalogView.swift, MisticaCatalog/Source/Catalog/MisticaSwiftUI/Components/FeedbackCatalogView.swift, Sources/MisticaSwiftUI/Utils/Backport.swift, Sources/MisticaSwiftUI/Utils/Modifiers/AccessibilityViewModifier.swift
Hi there!
This PR is to fix a bug with the accessibilityModifier modifier which was having an infinite recursion when called due to the availability blocks inside it. This was also causing crashes in apps using this feature.
Thanks to @jmpg93 we have been able to fix the bug by using a backport to avoid this infinite loop.
=> IOS-7708 Fix loop in accessibilityIdentifier

MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift, Sources/Mistica/Components/Sheet/Model/SheetConfiguration.swift, Sources/Mistica/Components/Sheet/View/SheetView.swift
Following the specs:
https://www.figma.com/file/nxToAYk7FGC86TS0mY61TU/Sheet?node-id=1697%3A9481
It was wrong:
But now it's
How??? I've added the two sizes to show an icon: 24x24 & 40x40. By default it will be 40x40 (copying the current behavior of the list cells)
=> IOS-7720 Fix asset size

MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogCroutonViewController.swift, Sources/Mistica/Components/Crouton/Domain/CroutonConfig.swift, Sources/Mistica/Components/Crouton/Presentation/CroutonController.swift, Sources/Mistica/Components/Crouton/Presentation/CroutonView.swift
https://jira.tid.es/browse/IOS-7902
This PR consists of adding the possibility to customize the time it takes for the Crouton component to disappear. By default, the time for a Crouton without actions is five seconds, and sometimes that may not seem long enough, for example when showing a warning to the user that he has no connection. 
What I have done is give freedom to the developer to choose that time for any style of Crouton. The design team they have proposed to provide a choice between 5 and 10 seconds.
=> IOS-7902 add a customisable time interval to dismiss

MisticaCatalog/Source/Catalog/MisticaSwiftUI/Components/SnackbarCatalogView.swift
[IOS-7918](https://jira.tid.es/browse/IOS-7918)
Hi guys, we had a problem with the snackbar catalog view that we were not able to select the styles. The issue was that we were applying the`endEditingOnTap` to all the views and that disable the taps everywhere.
=> IOS-7918 - Fix Crouton tap selection

Sources/MisticaSwiftUI/Components/Cards/DataCard.swift
Xcode 14.3 beta 2 is triggering a compilation error in DataCard component, due to we're using an optional binding with a non optional value.
=> IOS-8133 Fix compilation error for Xcode 14.3 beta 2

MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogCardsViewController.swift, MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSectionTitleViewController.swift
Hi there! 👋
With the recent breaking changes in the 21.0.0 version of Mistica: https://github.com/Telefonica/mistica-ios/compare/v20.2.0...v21.0.0
The TableViewCell named ListViewCell has been renamed to ListTableViewCell. Therefore, it is necessary to update two cell registers that were outdated with the last change and made the Catalog not work properly.
=> IOS-8146 Fix ListCellContent cell registered with new Mistica version

.github/workflows/build-mistica-catalog.yml
We want to create builds to be tested by Design, Devs, etc **before integrating the feature**.
The AppCenter project is hardcoded in [build-mistica-catalog](https://github.com/Telefonica/mistica-ios/blob/main/.github/workflows/build-mistica-catalog.yml#L47) and using 
will override our _Internal Enterprise_.
1. Create a new appCenter project (I took an existing one): https://appcenter.ms/orgs/Tuenti-Organization/apps/Mistica-SwiftUI-iOS
2. Parametrize the project (See this PR)
I've executed 
and it created
https://appcenter.ms/orgs/Tuenti-Organization/apps/Mistica-SwiftUI-iOS/distribute/releases/7
Action: https://github.com/Telefonica/mistica-ios/actions/runs/4384647422
To avoid forcing a release in a different branch, I've replaced the trigger with `push` …
=> Allow building alphas in Mistica

.github/pull_request_template.md, .releaserc
https://jira.tid.es/browse/IOS-8208
Every release, the Mistica Catalog must be bumped as Mistica already does. Currently, Mistica Catalog version is not pushed.
The problem is here:
https://github.com/Telefonica/mistica-ios/blob/274db414e3e1dee34e4cb3232b01f57d452cffe7/.releaserc#L9-L11
Every time the semantic-release is executed, it modifies both xcconfigs (Catalog & Mistica), bumping to the next version.
The problem is the Catalog xcconfig is not included there, then it is not pushed :(
See https://github.com/Telefonica/mistica-ios/actions/runs/4446829704/jobs/7807625092#step:4:135 which found only two files (Changelog.md & Mistica.xcconfig).
I've just added the Catalog config.
You can check that `./scripts/update-version.sh 1.2.3` is working properly, modifying both files. We'll check …
=> IOS-8208 Add MisticaCatalog config to be pushed with the version bumped

MisticaCatalog/Source/ColorsView.swift, Sources/MisticaCommon/MisticaConfig.swift, Sources/MisticaCommon/Styles/BrandStyle.swift
https://jira.tid.es/browse/IOS-8817
Allow customizing font weighs for custom mistica config like we already do for Colors and Assets. See how Zeus is configured:
https://github.com/Telefonica/zeus-ios/blob/5bc3f2963d0308a5d54f18f7f46e4cb68a4af0cd/App/iOS/AppDelegate.swift#L33
Add a new associated value in `.custom` enum case.
Executed in Zeus:
Before it was (MovES):
=> IOS-8817 Allow custom font weights

Sources/Mistica/Components/Cards/HighlightedCard.swift
[IOS-8932](https://jira.tid.es/browse/IOS-8932)
Make the button and labels visible for accessibility.
For an old reason, we were concatenating the title and subtitle in one `UIAccessibilityElement`. I talked with the QA team and in Android they have the title and subtitle separated, and this is reasonable and expected according to Figma. So we removed the `cardAccessibilityElement` and added the `horizontalStackView`to the `accessibilityElements` of the `HighlightedCard`
https://github.com/Telefonica/mistica-ios/assets/43632903/170d5c58-cd11-456b-bbb9-a42f123dbb39
=> IOS-8932 - Make visible to accessibility HighlightedCard button

Sources/Mistica/Components/Cards/HighlightedCard.swift
[IOS-8932](https://jira.tid.es/browse/IOS-8932)
QA team reported that the button "Try to ask aura something" that corresponds to the `actionButton` of the `HighlightedCard` is duplicated in their accessibility tool.
Remove it from the `accessibilityElements` because the button is accessible by default and now we do not have the `UIAccessibilityElement` for the card, removed in the [PR](https://github.com/Telefonica/mistica-ios/pull/275)
=> fix(HighlightedCard): actionButton duplicated for accessibility tool

Makefile, MisticaCatalog/MisticaCatalog.xcodeproj/project.pbxproj, Package.swift
IOS-9013
As explained in the document https://confluence.tid.es/display/CTO/%5BAPPS%5D+Shared+Spec%3A+Mistica+iOS+issues+with+duplicated+symbols, the current `Package.swift` creates two libraries `Mistica` and `MisticaSwiftUI` with the same `MisticaCommon` code added to each library. This causes duplicated symbols and unexpected behaviour when importing the two libraries in the same target.
Combine all Modules into a single `Mistica` library.
Run and build a project that uses Mistica and MisticaSwiftUI (E.g. MisticaCatalog), check that there are no longer duplicated symbols.
=> IOS-9013 Combine mistica into a single package to prevent duplicated symbols when importing Mistica and MisticaSwiftUI

Sources/Mistica/Components/Sheet/View/Fragments/List/Rows/InformativeRow.swift
[IOS-9113](https://jira.tid.es/browse/IOS-9113)
- Fix the component to fit in iOS 14.5 or less. The texts are not well shown
Info: The dot is centered on a single line label with the same specs than the visible label, but is in a deeper layer stackView.
- The component was using a dummy view to create the space for the dot in the front stackView. This dummy view has been removed and the stackView modifies the layout margin to replace this space.
=> fix(Bottom Sheet): Fix component to expand horizontally

Package.swift, Sources/Mistica/Components/Sheet/View/Fragments/List/Rows/ActionRow.swift, Sources/Mistica/Components/Sheet/View/Fragments/List/Rows/InformativeRow.swift, Sources/Mistica/Components/Sheet/View/Fragments/List/Rows/SingleSelectionRow.swift, Sources/Mistica/Utils/Extensions/URL+Utils.swift
https://jira.tid.es/browse/IOS-9461
Apple’s URL parsing implemented RFC1738/1808 standard and was changed to RFC3986 starting from iOS 17. Actually, it can produce problems with code written before, because now URL(string: "Invalid URL") is not nil. Apple updated the URL initializer for iOS 17 with a new Bool parameter encodingInvalidCharacters that has a default value (true) — it is what makes the behavior unpredictable and it needs to be handled.
We have added a custom initializer where we will pass our urlString and behind if we are in iOS 17 we will set the new parameter encodingInvalidCharacters to false so that the behavior is similar to what we had before and return nil if the URL is not valid.
This custom initializer will be the one that by default we will have to use for new URLs …
=> [IOS-9461] Fix URL(string:) behavior

MisticaCatalog/Source/Catalog/CatalogList.swift, MisticaCatalog/Source/Catalog/MisticaSwiftUI/Components/ListCatalogView.swift, MisticaCatalog/Source/ColorsView.swift, Sources/MisticaSwiftUI/Components/List/Cell.swift, Sources/MisticaSwiftUI/Components/List/README.md
IOS-9445
Hide last divider in mistica lists
- Add a modifier to hide the cell divider
- Update usages
- Update documentation
Before:
https://github.com/Telefonica/mistica-ios/assets/2429905/62fcd302-31c0-4a39-8ddd-05522587c822
After:
https://github.com/Telefonica/mistica-ios/assets/2429905/99220923-3fa1-4aeb-8583-65c3a2e9b226
=> IOS-9445 Hide last divider

Sources/Mistica/Components/Tabs/TabsView.swift
https://jira.tid.es/browse/SMARTWIFI-8301
Allow users of TabsView component to select a tabItem when needed.
This is needed in SmartWiFi to allow tabItem selection on controller swipe when used in complement with a UIPageController.
See following video:
https://github.com/Telefonica/mistica-ios/assets/23734068/5bb22d7f-6676-4fb8-802b-895511330a7d
- Add `deselectAll` method as we need to previously deselect all items before selecting the target controller on swipe (this prevents cumulating indicators in tabs)
- Make `selectTabItem(at:)` public so we can use it from outside.
See previously attached video.
=> fix(TabsView): Allows consumers to select an item and deselect all

Makefile, _templates/ColorTokenGenerator/MisticaColors/ToolkitColorsAction.ejs.t, _templates/ColorTokenGenerator/MisticaColors/UIToolkitColorsAction.ejs.t
https://jira.tid.es/browse/IOS-9672
When `mistica-design` adds a new color, it's not accessible due to we use `ColorToolkit+UIColor` & `ColorToolkit+Color` helper extensions.
I've not updated the palettes since it would affect production [out of scope]. I think Yayo is on it (https://github.com/Telefonica/mistica-ios/pull/327) but I had to help him adding some missing static methods https://github.com/Telefonica/mistica-ios/pull/327/commits/c7f2a0294f0671761a09f73cbffc718fe30c18fa which will be solved with these templates
Just added a couple of actions for Colors generator which generates those files.
`make skin ref=production`
- ✅  The process is success
- ✅  The app is built and works properly
=> IOS-9672 Add missing templates

MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogCroutonViewController.swift, MisticaCatalog/Source/Catalog/MisticaSwiftUI/Components/SnackbarCatalogView.swift, Sources/Mistica/Components/Crouton/Domain/CroutonConfig.swift, Sources/Mistica/Components/Crouton/Presentation/CroutonController.swift, Sources/Mistica/Components/Crouton/Presentation/CroutonView.swift, Sources/MisticaCommon/Components/Snackbar/Domain/SnackbarConfig.swift, Sources/MisticaSwiftUI/Components/Snackbar/Snackbar.swift, Sources/MisticaSwiftUI/Components/Snackbar/View+Snackbar.swift, Tests/MisticaSwiftUITests/UI/CroutonTests.swift, Tests/MisticaSwiftUITests/UI/SnackbarTests.swift
[IOS-9726](https://jira.tid.es/browse/IOS-9726) Fix a bug where the close button can only be configured with infinite duration
The crouton/scnakbar should be able to show the close button with any duration configured.
Remove the infiniteWithClose interval option and pass a flag which defines if the close button should be forced or not( if the duration is infinite and has no action defined, the close button will also be presented).
You can test it in the catalog.
=> IOS-9726 Fix close button with any duration

Sources/Mistica/Components/Lists/ControlPresets/NavigationPresetView.swift
[IOS-9694](https://jira.tid.es/browse/IOS-9694)
Make the chevron of the lists visible for QA tool
We just have to enable the property `isAccessibilityElement` and create and accesible variable for set the id if needed.
=> fix(List): Make list chevron accesibility identifier visible

Sources/Mistica/Components/Lists/ControlPresets/NavigationPresetView.swift, Sources/MisticaCommon/DefaultAccessibilityIdentifiers/DefaultAccessibilityIdentifiers.swift, Sources/MisticaCommon/DefaultAccessibilityIdentifiers/FeedbackAccessibilityIdentifiers.swift, Sources/MisticaCommon/DefaultAccessibilityIdentifiers/ListAccessibilityIdentifiers.swift, Sources/MisticaSwiftUI/Components/List/CellNavigationPreset.swift
[IOS-9694](https://jira.tid.es/browse/IOS-9694)
Add a default ID for the list chevron image.
We have brought from [iphoneapp](https://github.com/Telefonica/iphoneapp/blob/7b70716012437e1565e850314dc6d96e5320b8a2/Messenger/PlatformKit/Source/Testing/Accessibility/AccessibilityIdentifier.swift#L9) a struct called `DefaultAccessibilityIdentifier` where we have different properties to compose the identifier following the `Feature`, `Section` and `ElementType` defined as constants. This way we prepare mistica to unify the IDs with Android following the different ids configured in Figma, [like lists](https://www.figma.com/file/Be8QB9onmHunKCCAkIBAVr/branch/SY4mjjuquWijveRpvxvl0M/%F0%9F%94%B8-Lists-Specs?type=design&node-id=2811-5741&mode=design&t=g5taw3M4yCctMlm8-0)
To accomplish this issue we …
=> fix(AccessibilityIdentifiers): IOS-9694 - New struct for common Ids

Makefile
We found some issues executing tests due to the destination param looks working different due to the XC tools version.
See:
https://teams.microsoft.com/l/message/19:40b9dabcaf1a4abea1216117ac7c0596@thread.tacv2/1697557532308?tenantId=9744600e-3e04-492e-baa1-25ec245c6f10&groupId=992881f8-bbab-4891-8c17-ffe99ba6f43b&parentMessageId=1697532771278&teamName=Apps%20Team&channelName=iOS&createdTime=1697557532308
I've updated the destination value to ensure it will work with the right device.
It just affects to tests so if tests pass...
=> Improve destination param

Sources/Mistica/Components/Callout/Callout.swift, Sources/Mistica/Components/Callout/CalloutConfiguration.swift, Sources/MisticaSwiftUI/Components/Callout/Callout.swift
[IOS-9818](https://jira.tid.es/browse/IOS-9818) Callout inverse variant
We need to behave like Android and allow an inverse (bakground) variant that will be enabled by default with a **backgroundContainer** color, and **backgroundAlternative** when not enabled.
See Android [commit](https://github.com/Telefonica/mistica-android/commit/069dbd6b5ebf0d08d4e0137250ded440791e7f13#diff-c40f0e2acf9b132af8b3f480beeb268b726b561b932380e950e883b0326f9babR163)
=> feat(Callout): IOS-9818 Adding inverse variant

Makefile
https://jira.tid.es/browse/IOS-9708
When we create a new Mistica release, it generates a new Mistica Catalog app automatically. This process is failing:
https://github.com/Telefonica/mistica-ios/actions/workflows/build-mistica-catalog.yml?query=event%3Arelease
In the last execution, @WanaldinoTelefonica saw this warning:
https://github.com/Telefonica/mistica-ios/actions/runs/7986232134/job/21806207849#step:6:82
I don't know if it's the same issue as:
> https://teams.microsoft.com/l/message/19:40b9dabcaf1a4abea1216117ac7c0596@thread.tacv2/1708358820438?tenantId=9744600e-3e04-492e-baa1-25ec245c6f10&groupId=992881f8-bbab-4891-8c17-ffe99ba6f43b&parentMessageId=1708358444203&teamName=Apps%20Team&channelName=iOS&createdTime=1708358820438
but at least I'm going to add `-destination` param to …
=> Add destination to archive script

Sources/Mistica/Utils/Extensions/UIBarButtonItem+Utils.swift
https://jira.tid.es/browse/IOS-9656
To give support to be able to download images from URL that are in SVG format and that we can configure them as image in components like UIButton. This will allow that in apps like Novum we can configure the navigation bar buttons with SVG URLs.
For this purpose, a setImageFromURL method has been implemented in a public extension of UIButton. This method will make use of the SDWebImage library that allows us to download images in SVG format and set them inside the UIButton image.
=> IOS-9656 Add SVG support in UIButtons images

.github/workflows/ci.yml, .github/workflows/record-screenshots.yml, CONTRIBUTING.md
[IOS-9864](https://jira.tid.es/browse/IOS-9864)
Update the GitHub action to record the screenshots so it also executes the tests.
Also change the action so it is executed by inserting `/record-screenshots` as comment on a PR to avoid branch mistakes and to be able to set the commit and the PR status after passing the tests.
- Execute the tests after recording the screenshots. 
- Launch the action by commenting on a PR.
- Update the latest commit status and thus the PR status with the tests result.
=> IOS-9864: Update record-screenshots to also pass the tests

Sources/Mistica/Components/Cards/DataCard.swift, Sources/Mistica/Components/Cards/Internals/CardCommonContent.swift, Sources/Mistica/Utils/Views/StackViewContentItem.swift
[IOS-9915](https://jira.tid.es/browse/IOS-9915)
Accessibility identifier was not  being assigned to the expected element. 
The problem is solved by declaring identifier properties till the end of the elements chain of a DataCard.
=> FIX - Add accessibility identifier to dataCard elements

Sources/Mistica/Components/Callout/Callout.swift, Sources/Mistica/Components/Lists/ListCellContentView.swift, Sources/MisticaCommon/DefaultAccessibilityIdentifiers/CalloutAccessibilityIdentifiers.swift, Sources/MisticaCommon/DefaultAccessibilityIdentifiers/DefaultAccessibilityIdentifiers.swift
[IOS-9930](https://jira.tid.es/browse/IOS-9930)
List rows don't have default accessibility identifiers, so they have been assigned.
Also, according to Figma callout ids, they were incorrect and this PR fix them by removing section value from their id. Now, 
DefaultAccessibilityIdentifier.Section will be optional.
=> Add default ids for listCellContentView and fix callout component ids

Sources/MisticaSwiftUI/Components/Button/MisticaButtonStyle.swift
[IOS-9962](https://jira.tid.es/browse/IOS-9962) Wrong colors in misticaLinkInverse button style
Fix the button style 'misticaLinkInverse' text color.
It was detected in Wallet that we are using 'textButtonSecondaryInverse' instead of 'textLinkInverse' as defined in [here](https://www.figma.com/file/koROdh3HpEPG2O8jG52Emh/%F0%9F%94%B8-Buttons-Component-Specs?type=design&node-id=3566-1600&mode=design&t=03d7Rpp4UEOAGUix-4)
Change 'textColor' to 'textLinkInverse'
=> IOS-9962 - Fix textColor token in misticaLinkInverse button style

MisticaCatalog/MisticaCatalog.xcodeproj/project.pbxproj, MisticaCatalog/Source/Catalog/MisticaSwiftUI/Components/CarouselCatalogView.swift, Sources/MisticaSwiftUI/Components/Carousel/Carousel+Configuration.swift, Sources/MisticaSwiftUI/Components/Carousel/Carousel.swift, Sources/MisticaSwiftUI/Components/Carousel/Carousels/PaginatedCarousel.swift, Sources/MisticaSwiftUI/Components/Carousel/PageControl.swift
[IOS-9973](https://jira.tid.es/browse/IOS-9973)
As detected in [Wallet](https://jira.tid.es/browse/WLLT-380), Carousel component is missing the option to show the page control bullets with Inverse style as specified [here](https://www.figma.com/file/WCkDDzlXE16R6yXaljxddj/Mística-Mobile?type=design&node-id=4229-8966&mode=design&t=o3U0ygd67GFWmFrs-4)
- Add an inverse style option to PageControl
- Add a CarouselBulletsStyle to the Carousel with values normal/inverse
- Modify previews and MisticaCatalog backgrounds in the Carousel to be able to see the white bullets
https://github.com/Telefonica/mistica-ios/assets/2358107/1ab889b4-7ea0-4385-a35f-80e27ae53f6f
=> IOS-9973 - Add inverse style option for the page bullets in Carousel

_templates/ColorTokenGenerator/BrandColors/BrandColorsAction.ejs.t, _templates/ColorTokenGenerator/MisticaColors/MisticaColorsAction.ejs.t, _templates/ColorTokenGenerator/MisticaColors/ToolkitColorsAction.ejs.t, _templates/ColorTokenGenerator/MisticaColors/UIToolkitColorsAction.ejs.t
https://jira.tid.es/browse/IOS-10003
Due to the future new gradient tokens and as an improvement to the robustness of the color token importers it is necessary to download only those tokens from the color palette that are of color type. If in the future the color tokens were of gradient type it would create an issue.
Type checkers have been added to each template involved in the generation of color tokens.
It has been verified that the script is correct by running in terminal:
`make skin ref=production`
The result was that **the new generated color palette doesn't contain the existing gradient token** in the mistica-design json:
https://github.com/Telefonica/mistica-design/blob/e58edd73c4e4877fc8b902f8a2d9a31da5ca8b8a/tokens/movistar.json#L623
**The other tokens remain the same and as …
=> IOS-10003 Fix color token importers with type filter

Sources/Mistica/Components/Header/HeaderView.swift, Sources/Mistica/Components/Title/TitleView.swift
[IOS-9797](https://jira.tid.es/browse/IOS-9797) VIVO Novo app accessibility: Titles in native contents
Set as headers:
1. Seguranca e privacidade (Profile)
2. Acceso biometrico e PIN (Profile -> Seguranca e privacidade)
3. PIN entering screens (Profile -> Seguranca e privacidade -> Acceso biometrico e PIN)
4. Acesso a sua conta (Profile -> Acesso a sua conta)
5. Dispositivo atual (Profile -> Acesso a sua conta)
6. Outros dispositivos (Profile -> Acesso a sua conta)
To identify elements as headers, we will use accessibilityTraits using `.header` value. Using this trait, VoiceOver will speak elemens as headers.
Exposed accessibilityTraits for HeaderView and TitleView titles.
Checking the code
=> IOS-9797 VIVO Novo app accessibility: Titles in native contents

Sources/Mistica/Components/Feedback/FeedbackView.swift, Sources/MisticaSwiftUI/Components/Feedback/Feedback.swift
[IOS-9786](https://jira.tid.es/browse/IOS-9786) VIVO Novo app accessibility Assinaturas: decorative images/animation to ignore
Exclude feedback icons from accessibility in order to not being spoken by VoiceOver
Used `isAccessibilityElement=false` in UIKit and `.accesibilityHidden(true)` in SwiftUI to exclude icons
Use Mistica Catalog: Activate VoiceOver and check that icons are not accessibile via VoiceOver
https://github.com/Telefonica/mistica-ios/assets/4386305/55fffa5c-e076-4280-9d98-e31aacc7377f
https://github.com/Telefonica/mistica-ios/assets/4386305/fbab19f3-a66e-4726-a729-e32d2483df61
=> IOS-9786 VIVO Novo app accessibility Assinaturas: decorative images/animation to ignore

.github/workflows/record-screenshots.yml
Update the record screenshots on PR comment GitHub action so the launched workflow URL and when finished, the final result, is shown o the PR comment that launched the action
=> Update record-screenshots action so the status is updated in the PR comment

Sources/Mistica/Utils/Extensions/UIBarButtonItem+Utils.swift
[IOS-10056](https://jira.tid.es/browse/IOS-10056) TopBarButtonItemPresenter.downloadIcons crash
As part of [IOS-10056](https://jira.tid.es/browse/IOS-10056) fix which reverts changes done in https://github.com/Telefonica/mistica-ios/pull/350 we need to restore this code
Restored `UIButton` extension method `setImageFromURL(url:urlForDarkMode:defaultImage:`
Just check the code
=> Reverted change to fix /IOS-10056

MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogHeaderViewController.swift, Sources/Mistica/Components/Header/HeaderView.swift
[IOS-10266](https://jira.tid.es/browse/IOS-10266) [iOS] Header does not display correctly in initial permissions with iOS 14
in iOS 14 the Header component is not displayed correctly, for example in the initial permissions windows.
There seems to be a problem in iOS 14 when using `layoutMargins` as when integrating it as _Header_ of a _tableView_ it does not calculate the height correctly and the component is displayed incorrectly. 
|iOS 14 iPhone Xr|iOS 17.2 iPhone 14 Pro|
|--|--|
|<img src="https://github.com/Telefonica/mistica-ios/assets/1004932/a43fdb6c-d55f-4d79-9db7-778aa4013653"/>|<img src="https://github.com/Telefonica/mistica-ios/assets/1004932/e1dcb2ca-0081-4275-aec0-12b54dec4258"/>|
You can use the build generating in Mistica Alpha …
=> IOS-10266 [iOS] Header does not display correctly in initial permissions with iOS 14

Sources/Mistica/Components/Sheet/View/SheetViewController.swift
[IOS-10347](https://jira.tid.es/browse/IOS-10347) Native bottom sheet to be closable and have the right title semantics
As part of [IOS-10347](https://jira.tid.es/browse/IOS-10347) we need to set sheet's titles as header in order to be read as headers by VoiceOver
Set sheet's tilte label accessibility trait to header
The title should be spoken as "<title_content>, title" by VoiceOver
| Old | New |
|---|---|
| https://github.com/Telefonica/mistica-ios/assets/4386305/1a0ddca7-bf40-451c-8ce9-d24c9a20cc32 | https://github.com/Telefonica/mistica-ios/assets/4386305/ca1e6474-5171-44bc-a3e5-0bcc4746fdb2 |
=> Set sheet's title as header for accessibility

Sources/Mistica/Components/Lists/CellStyle+Toolkit.swift, Sources/Mistica/Components/Lists/ListCellContentView.swift, Sources/MisticaCommon/Colors/BlauColorPalette.swift, Sources/MisticaCommon/Colors/ColorToolkit+Color.swift, Sources/MisticaCommon/Colors/ColorToolkit+UIColor.swift, Sources/MisticaCommon/Colors/MisticaColor.swift, Sources/MisticaCommon/Colors/MisticaColors.swift, Sources/MisticaCommon/Colors/MovistarColorPalette.swift, Sources/MisticaCommon/Colors/O2ColorPalette.swift, Sources/MisticaCommon/Colors/O2NewColorPalette.swift, Sources/MisticaCommon/Colors/TelefonicaColorPalette.swift, Sources/MisticaCommon/Colors/TuColorPalette.swift, Sources/MisticaCommon/Colors/VivoColorPalette.swift, Sources/MisticaCommon/Colors/VivoNewColorPalette.swift
https://jira.tid.es/browse/IOS-10407
Update the Mistica tokens, specifically the VivoNew token for the `textAppBar` and the `backgroundContainerBrand` token which can now be a gradient in O2New.
This PR is a fix of the PR generated by @yceballost but with more information and adapted to be integrated:
https://github.com/Telefonica/mistica-ios/pull/380
The most relevant change is the `backgroundBrandContainer` that when taking values of solid color and gradient in function of the skin needs to be a `MisticaColor`.
This change affects the cells of Lists of type boxed inversed.
=> IOS-10407 Update textAppBar and backgroundContainerBrand tokens

Sources/MisticaSwiftUI/Components/Inputfield/InputField.swift, Sources/MisticaSwiftUI/Components/Inputfield/LegacyTextField.swift
[WLLT-1488](https://jira.tid.es/browse/WLLT-1488)
- Add a numeric type to InputField that shows the numeric keyboard
- Add the option to set textContentType to activate the autocompletion of emails, phone numbers, etc
- Add a new Style `numeric`
- Set the keyboard type to `numberPad` for the `numeric` style
=> feat(InputField): add option to set textContentType

Sources/MisticaCommon/Components/Snackbar/Domain/SnackbarConfig.swift, Sources/MisticaSwiftUI/Components/Snackbar/Snackbar.swift
[WLLT-1516](https://jira.tid.es/browse/WLLT-1516)
The current way of setting the accessibility identifier of the snarckbar title does not work for the SwiftUI modifier because the methods defined to set it are defined in Snackbar, but the SwiftUI modifier returns `some View` 
Use the existing SnackbarConfig (used to set the title) to set also the accessibility label and identifier if needed
=> feat(Snackbar): allow setting the accesibility identifier via SnackbarConfig

Sources/Mistica/Components/Crouton/Presentation/CroutonController.swift, Sources/Mistica/Components/Crouton/Presentation/OngoingCrouton.swift, Tests/MisticaTests/UI/CroutonTests.swift
[IOS-10309](https://jira.tid.es/browse/IOS-10309)
- Allow crouton to be shown in a specific viewController
- Store the viewController on the ongoingCroutons (weak reference as we don't want to retain it)
- If the viewController is defined, don't look for the top most viewController
=> iOS 10309 crouton on screen

.github/workflows/generate-mistica-tokens.yml, .github/workflows/mistica-skin-generator-tests.yml
https://jira.tid.es/browse/IOS-10444
Having the generation fixed here https://github.com/Telefonica/mistica-ios/pull/387, we need to integrate it in GitHub Actions.
Now it's simpler since it's just a node execution, see the code.
I've added the tests execution too.
I've forced it manually:
- Action: https://github.com/Telefonica/mistica-ios/actions/runs/10057041206/job/27797170500#step:5:12
I've forced it manually:
- Action: https://github.com/Telefonica/mistica-ios/actions/runs/10057833337
- PR: https://github.com/Telefonica/mistica-ios/pull/392
=> IOS-10444 Mistica importer from GH Actions

MisticaCatalog/MisticaCatalog.xcodeproj/project.pbxproj, MisticaCatalog/Source/Catalog/MisticaSwiftUI/Components/EmptyStateCatalogView.swift, MisticaCatalog/Source/Catalog/MisticaSwiftUI/Components/FeedbackCatalogView.swift, MisticaCatalog/Source/Catalog/MisticaSwiftUI/Components/ListCatalogView.swift, MisticaCatalog/Source/Catalog/MisticaSwiftUI/Components/SnackbarCatalogView.swift, MisticaCatalog/Source/Catalog/MisticaSwiftUI/Components/TagCatalogView.swift, Package.resolved, Package.swift, Sources/Mistica/Components/Button/Button.swift, Sources/Mistica/Components/Checkbox/Checkbox.swift, Sources/MisticaSwiftUI/Components/Inputfield/InputField.swift
https://jira.tid.es/browse/IOS-10545
With the release of XCode 16 and Swift 6, new warnings have emerged that can be fixed along with old ones.
The following changes have been made:
- AppCenter framework has been updated to its latest version due to an error in finding an AppCenterDistribute .h file.
- Lottie framework has also been updated as its git address had been changed and it could not find the repository.
- In Swift 6 a new warning has appeared in those modules that conform types like Identifiable, Hashable... in an external way to the module, this can cause that if the module evolves in the future and includes this type there can be conflicts in the code that give error. More information here: 
https://github.com/swiftlang/swift-evolution/blob/main/proposals/0364-retroactive-confo …
=> IOS-10545 Fix warnings in XCode 16

MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogButtonsViewController.swift, MisticaCatalog/Source/Catalog/MisticaSwiftUI/Components/ButtonCatalogView.swift
> [!WARNING]
https://jira.tid.es/browse/IOS-10753
wrong background in SwiftUI catalog when it's dark mode and shows inverse links.
It's already solved in the UIKit catalog, so I've taken the same background colors.
=> IOS-10753 Fix background

Sources/Mistica/Components/Feedback/Model/FeedbackConfiguration.swift
https://jira.tid.es/browse/IOS-10544
Due to the migration to Swift 6 with strict concurrency that we are doing in Novum it is necessary to add some changes in the completion of Feedback so that it can be compatible with apps migrated in Swift 6.
Since it is a visual component that requires UI actions, its completion action is isolated in a main actor environment and its parameters will be `Sendable` to ensure safe concurrency.
This fix will be used from this PR in Novum:
https://github.com/Telefonica/iphoneapp/pull/1792
=> IOS-10544 Add safe concurrency in Feedback completion

MisticaCatalog/MisticaCatalog.xcodeproj/project.pbxproj, MisticaCatalog/Source/Catalog/CatalogList.swift, MisticaCatalog/Source/Catalog/MisticaSwiftUI/Components/ViewStatesCatalogView.swift, Sources/MisticaSwiftUI/Components/ViewStates/LoadErrorView.swift
https://jira.tid.es/browse/IOS-10800
As a performance objective to make SwiftUI components, ViewStates component will be migrated from UIKit to SwiftUI.
A new component similar to the component in UIKit has been created and added inside the Catalog.
**FOR DESIGN MEMBER** (@AnaMontes11) : There is a difference between the buttons we have for SwiftUI and the UIKit buttons, I'm not clear which one should be the correct one since I can't find references to the Design of this component. I hope that in the revision of this PR a member of Design can clarify it.
If the SwiftUI design is correct, it could be used as a base and apply in UIKit a wrapper that encapsulates the SwiftUI design to use the same design in all platforms.
| SwiftUI | UIKit |
|---|---|
| <img width="330" alt="Screenshot …
=> IOS-10800 Make ViewStates component in SwiftUI

Sources/MisticaCommon/Extensions/Bundle+Mistica.swift
In Wallet, all the previews crash due to an old fix implemented that seems to fail with the latest Xcode.
This PR removes that fix as it is the cause of the crashes and I don't see any other errors reverting it.
Remove the fix and go back to using Bundle.module
The PR is done on the Swift 6 branch as Wallet is already using Swift 6, I have not tested it in main
=> Remove misticaCommon fix to an old Bundle.module bug

.github/workflows/generate-mistica-tokens.yml, scripts/mistica-skin-generator/index.js
https://jira.tid.es/browse/IOS-10974
When `mistica-design` job trigger our `generate-mistica-tokens.yml`, it fails:
https://github.com/Telefonica/mistica-design/actions/runs/13055903096/job/36426747377#step:3:17
`ref` param is unexpected.
Allow this (optional) param.
- Job: https://github.com/Telefonica/mistica-ios/actions/runs/13074654923/job/36483749212
- Output: https://github.com/Telefonica/mistica-ios/pull/424
=> IOS-10974 Allow ref param

Sources/MisticaSwiftUI/Components/Carousel/Carousels/TrackableScrollView.swift, Sources/MisticaSwiftUI/Components/Tabs/Tabs.swift, Sources/MisticaSwiftUI/Utils/Modifiers/SizeViewModifier.swift
https://jira.tid.es/browse/IOS-10545
Concurrency bugs have been detected that only appear in XCode version 16.2. 
The fact that they do not appear in the other versions of XCode does not mean that it is a concurrency error that must be fixed.
The closure of the `onPreferenceChange` method is `Sendable` and therefore if we want to access an isolated value in `MainActor` we must guarantee that the context where it is accessed is also `MainActor`.
However, `onPreferenceChange` method is not isolated in `MainActor` so it is necessary to isolate its closure in a `Task` that is.
You should not see any compile errors in XCode 16.2.
=> IOS-10545 Fix Strict Concurrency in XCode 16.2

Package.resolved, Package.swift
> [!WARNING]
https://jira.tid.es/browse/IOS-11150
Update lottie sdk to latest 4.5.1. 
https://github.com/airbnb/lottie-spm/tags
Note: 
To avoid dependency conflicts and ensure compatibility, apps that integrate Mistica and Lottie should update to the same version of Lottie.
Update sdk; no changes needed
Tested proper behaviour.
https://github.com/user-attachments/assets/5ad73e2a-7946-4fb5-a892-7fdbac3bab82
=> IOS-11150 update lottie sdk to 4.5.1

Sources/Mistica/Components/Button/Button.swift, Sources/Mistica/Components/Feedback/FeedbackStyle+Toolkit.swift, Sources/Mistica/Components/Feedback/Model/FeedbackConfiguration.swift, Sources/Mistica/Components/Sheet/Model/SheetConfiguration.swift
https://jira.tid.es/browse/IOS-11319
To silence concurrency-related warnings, certain types must be added as Sendables to ensure concurrency.
Add Sendable in `SheetConfiguration` and `FeedbackConfiguration`.
=> IOS-11319 Fix Sendable types for concurrency warnings

.github/workflows/release.yml
In order to notify to teams in public runners using the internal action we need the private novum token
This is to fix release executions like: 
https://github.com/Telefonica/mistica-ios/actions/runs/15303623918/job/43050533903#step:6:34
=> Add flow token to notify

MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSnackbarViewController.swift, Sources/Mistica/Components/Snackbar/Presentation/SnackbarView.swift, Sources/MisticaCommon/Components/Snackbar/Domain/SnackbarConfig.swift
> [!WARNING]
https://jira.tid.es/browse/IOS-11095
The Snackbar specifications have been updated for accessibility. For critical persistent Snackbars, the focus will now automatically move to ensure better accessibility.
A new parameter has been added to move the focus to persistent Snackbars. Additionally, a delay parameter has been introduced to ensure the focus movement, for cases when UI changes are still rendering or have animations.
https://github.com/user-attachments/assets/25bf7ad5-edc8-43d3-8c8d-ec97ca598022
=> Ios 11095 automatic focus snackbar critical cases

Sources/Mistica/Components/Feedback/FeedbackView.swift
Set primary and secondary buttons as non-accessibility elements during setup, then re-enable accessibility after animations complete. This ensures accessibility elements are only active when appropriate, improving user experience for assistive technologies.
[IOS-11534](https://jira.tid.es/browse/IOS-11534)
- Fix the first element spoken by VoiceOver when opening FeedbackViewController modally
- Temporarily disable button's accessibility until the title/subtitle views are visible 
https://github.com/user-attachments/assets/a2132596-971b-401d-a3e3-c35f58cccbdc
=> FIX - Fix voiceOver spoken first element in Feedback view - refs IOS-11534

Sources/Mistica/Components/Button/Button.swift, Sources/Mistica/Components/Sheet/View/BottomSheetPresentation/BottomSheetInteractiveDismissalTransition.swift
> [!WARNING]
[IOS-11539](https://jira.tid.es/browse/IOS-11539)
[IOS-11547](https://jira.tid.es/browse/IOS-11547)
Fix compilation problems with XCode 26 Beta 1
The changes involve wrapping certain UI-related code in `Task { @MainActor in ... }` blocks.
* [`Sources/Mistica/Components/Button/Button.swift`](diffhunk://#diff-362078373d69bbbe7bda182440bef91c7f97cd04f4a76f00e6459135eaae143eR361-R365): Updated the animation completion block in the `Button` component to ensure that `UIAccessibility.post` and `updateTraits()` are executed on the main thread.
* `Sources/Mistica/Components/Sheet/View/BottomSheetPresentation/BottomSheetInteractiveDismissalTransition.swift`: 
- Ensured that `offsetAnimator` and `heightAnimator` operations within …
=> IOS-11539 IOS-11547 Fix compilation problems with XCode 26 Beta 1

Sources/Mistica/Components/Snackbar/Presentation/SnackbarView.swift
https://jira.tid.es/browse/IOS-11606
Constraint errors occur when displaying and closing a Mistica snackbar from other projects.
This PR fixes an Auto Layout conflict that occurred when dismissing a SnackbarView. The issue was caused by a hardcoded height constraint (heightAnchor.constraint(equalToConstant:)) being added during the dismissal animation, which conflicted with existing constraints tied to the view’s layout margins and internal stack views.
✅ Changes made:
- Removed the forced heightAnchor constraint during snackbar dismissal.
- Dismissal is now handled purely by updating the bottomConstraint and animating the opacity (alpha).
- Preserved existing layout logic and animation behavior (layoutIfNeeded and fadeStackViewOut()).
No constraints errors are triggered when snackbar is …
=> IOS-11606 Fix snackbar constraint when dismiss

Sources/Mistica/Components/Callout/Callout.swift
[IOS-11847](https://jira.tid.es/browse/IOS-11847)
- Make sure the callout close view is accessible
- Converting the image view to a UIButton
=> EDIT - Make Callout's close image a button and accessible - IOS-11847
