Telefonica/mistica-ios

- .github/workflows/build-mistica-catalog.yml
[LIFE-8720](https://jira.tid.es/browse/LIFE-8720) Add apple certs as env var for un/installing apple certs from vault on the fly
> LIFE-8720 add apple certs as env var

- Mistica/Source/Components/Feedback/FeedbackView.swift
Add identifiers to feedback view as requested:
(default IDs of Mistica Feedback screen component)
icon
title
subtitle
first_button
> fix(Feedback): Accesibility identifiers for feedback

- Mistica/Source/Components/Feedback/FeedbackViewController.swift
(default IDs of Mistica Feedback screen component)
icon
title
subtitle
first_button
Forgot to add to the public viewController
> Fix(Feedback): Add accessibility to public viewController

- Mistica.xcodeproj/project.pbxproj
- Mistica/Source/Components/Feedback/FeedbackView.swift
- Mistica/Source/Utils/DefaultIdentifiers/DefaultIdentifiers.swift
Need to create default identifiers for FeedbackView
As Edu said we should create a default value for Mistica components and at the same time be able to change it from outside
> Fix(Feedback): Default identifiers for Feedback

- Mistica/Source/Components/Cards/Internals/CardButtonsView.swift
- Mistica/Source/Components/Cards/Internals/CardCommonContent.swift
- Mistica/Source/Components/Cards/MediaCard.swift
- Mistica/Source/Components/Feedback/FeedbackView.swift
- Mistica/Source/Utils/DefaultIdentifiers/DefaultIdentifiers.swift
Added default accessibilityIds to media card elements and add the chance to customize them
> fix(MediaCard): Missing accessibility ids on the Media Card - SMARTWIFI-4701

- Mistica.xcodeproj/project.pbxproj
- Mistica/SupportFiles/Mistica.xcconfig
Update version number in order to do a new release for 14.2.3
> Update Mistica version to 14.2.3

- Sources/Mistica/Components/Sheet/README.md
Hi there!
This PR has the sole purpose of triggering a version change after the integration of the previous PR:
https://github.com/Telefonica/mistica-ios/commit/fd7e08c4756023432ab12c922b84f0cac17c335d
This PR will be integrated with a commit with the appropriate syntax for such version change.
> IOS-7624 Fix Sheet readme

- MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
- Sources/Mistica/Components/Sheet/View/SheetView.swift
- Sources/Mistica/Utils/Extensions/UIImageView+URL.swift
https://jira.tid.es/browse/IOS-7725
The icons are being loaded in a sync flow. It blocks the view creation and then the presentation (See the ticket->video).
I've moved to an async flow to load the icons and then, fix this ticket.
We will work on placeholders, error cases, etc in the future
https://user-images.githubusercontent.com/9945756/192541308-d084e469-4e76-4a26-911c-47769e00c97b.mov
> IOS-7725 Load icons asynchronously

- Mistica/Source/Components/Tag/TagView.swift
https://jira.tid.es/browse/SMARTWIFI-4957
Added an accessibilityIdentifier for the label of tagView
> Add accessibilityIdentifier to the label in tagView

- Sources/MisticaSwiftUI/Components/Inputfield/LegacyTextField.swift
When you place a TextField into a GeometryReader + ScrollView you get the following issue:
https://user-images.githubusercontent.com/216846/202180706-f40eb214-0b23-4ec7-b55e-63d98de74d58.mov
After removing the asynch everything works fine
https://user-images.githubusercontent.com/216846/202180897-688537a8-e96c-47d2-9841-70177906935a.MP4
> fix(LegacyTextFieldCoordinator): Fixing focus

- README.md
The Fonts readme is on a different path
> Modify Readme Fonts path

- .github/workflows/build-mistica-catalog.yml
- .github/workflows/release.yml
According to this github repo, latest Node.js version for actions is 18.13.0
> Update Node to latest version available

- Sources/MisticaCommon/Fonts/FontToolkit+Font.swift
Due to a copy-paste, I found some typos
> IOS-8196 Fix font weights

- Package.swift
- Sources/Mistica/Utils/Extensions/UIImageView+URL.swift
[IOS-9246](https://jira.tid.es/browse/IOS-9246)
- Change SDWebImageSVGNativeCoder dependecy into SDWebImageSVGCoder
- Change Package.swift dependency
- Update the addition of the coder
> fix(BottomSheet): Changed SVG coder

- Makefile
[IOS-9755](https://jira.tid.es/browse/IOS-9755)
- Bump xcode version to xcode 15.2
> chore (Xcode): Bump XCode version to 15.2

- Sources/Mistica/Components/Callout/Callout.swift
- Sources/Mistica/Components/Callout/Internals/CalloutButtons.swift
- Sources/Mistica/Components/Callout/Internals/CalloutContentBase.swift
- Sources/Mistica/Components/Callout/Internals/CalloutMessagesContent.swift
- Sources/Mistica/Components/Callout/Internals/CalloutTitleActions.swift
- Sources/Mistica/Components/Callout/Model/CalloutButton.swift
- Sources/Mistica/Components/Cards/DataCard.swift
- Sources/Mistica/Components/Cards/Model/CardButton.swift
- Sources/MisticaCommon/DefaultAccessibilityIdentifiers/CalloutAccessibilityIdentifiers.swift
- Sources/MisticaCommon/DefaultAccessibilityIdentifiers/DataCardAccessibilityIdentifiers.swift
[IOS-9915](https://jira.tid.es/browse/IOS-9915) 
This PR adds default accessibility identifiers to DataCard and Callout elements.
> Add default and custom accessibility identifiers to Callout and DataCard refs IOS-9915

- Sources/Mistica/Utils/Extensions/UIBarButtonItem+Utils.swift
Minor change to fix previous commit [https://github.com/Telefonica/mistica-ios/pull/364](#364) semantic release typo
Minor comment text change
> Fix for previous commit semantic release typo

- CONTRIBUTING.md
- Sources/MisticaCommon/Fonts/README.md
no changes to the interface
https://jira.tid.es/browse/IOS-10376
Proposal to update README information and fonts urls.
Check the README  and the new URLs are correct.
> Ios 10376 update mistica readme

- Package.swift
- Sources/Mistica/Components/Filter/Filter.swift
- Sources/Mistica/Components/Filter/SegmentCell.swift
- Sources/Mistica/Components/Tabs/TabItemViewCell.swift
- Sources/MisticaCommon/Fonts/FontStyle.swift
- Sources/MisticaSwiftUI/Components/Button/MisticaButton.swift
- Sources/MisticaSwiftUI/Components/Button/ScaledMisticaButton.swift
- Sources/MisticaSwiftUI/Components/Carousel/Carousel.swift
- Sources/MisticaSwiftUI/Components/Carousel/Carousels/FreeCarousel.swift
- Sources/MisticaSwiftUI/Components/Carousel/PageControl.swift
- Sources/MisticaSwiftUI/Components/Inputfield/LegacyTextField.swift
- Sources/MisticaSwiftUI/Components/Tabs/Tabs.swift
- Sources/MisticaSwiftUI/Utils/Backport.swift
- Sources/MisticaSwiftUI/Utils/Extensions/Color+Utils.swift
- Sources/MisticaSwiftUI/Utils/Extensions/View+Utils.swift
- Tests/MisticaSwiftUITests/UI/CarouselTests.swift
- Tests/MisticaSwiftUITests/UI/TabsTests.swift
https://jira.tid.es/browse/IOS-10383
Upgrade all internal Mistica dependencies to iOS 14 minimum.
- The `.package` has been updated to iOS v14.
- Removed the iOS 13 exclusive logic and the checkers that checked if we were on iOS 14 or earlier.
- Removed iOS 14 and iOS 13 availables.
> IOS-10383 Upgrade to iOS 14

- Sources/Mistica/Components/Crouton/Presentation/CroutonController.swift
> Add missing doc

- .github/workflows/build-mistica-catalog-firebase.yml
Update secret to match the firebase secret naming used in other apps https://github.com/Telefonica/tf-github-novum-repos/pull/1711
> Update Mistica firebase secret

- .github/workflows/release.yml
[IOS-11147](https://jira.tid.es/browse/IOS-11147) Update Semantic Release to v24.2.3
Update Semantic Release to the latest available version to solve an issue with the release GA.
Update the release workflow where the semantic release has the fixed version
Launching the release GA...
> IOS-11147 Update semantic release to v24.2.3

- Sources/Mistica/Components/Button/Button.swift
- Sources/Mistica/Components/Feedback/FeedbackView.swift
- Sources/Mistica/Components/Sheet/View/BottomSheetPresentation/BottomSheetInteractiveDismissalTransition.swift
[IOS-11547](https://jira.tid.es/browse/ IOS-11547)
Fix build for on xcode 26
> EDIT - fix ios26 support - refs IOS-11547
